export const customers = [
  {
    id: "1c",
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    id: "2c",
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    id: "3c",
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    id: "4c",
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    id: "5c",
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    id: "6c",
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    id: "7c",
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    id: "8c",
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },
  {
    id: "9c",
    customerName: "Rosie Simpson",
    company: "Microsoft",
    phoneNumber: "(111)459-12-56",
    email: "ros@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    id: "10c",
    customerName: "Hermione Kline",
    company: "Facebook",
    phoneNumber: "(522)443-89-12",
    email: "her@facebook.com",
    country: "United States",
    status: "Active",
  },
  {
    id: "11c",
    customerName: "Eden Clements",
    company: "Facebook",
    phoneNumber: "(263)645-17-79",
    email: "eden@facebook.com",
    country: "United States",
    status: "Active",
  },
  {
    id: "12c",
    customerName: "Annie Copeland",
    company: "Microsoft",
    phoneNumber: "(230)227-91-26",
    email: "ann@microsoft.com",
    country: "United States",
    status: "Inactive",
  },
  {
    id: "13c",
    customerName: "Rosa Stryk",
    company: "Facebook",
    phoneNumber: "(555)459-12-56",
    email: "rosa@facebook.com",
    country: "Ukraine",
    status: "Active",
  },
  {
    id: "14c",
    customerName: "Hery Klyni",
    company: "Microsoft",
    phoneNumber: "(222)478-19-92",
    email: "hery@microsoft.com",
    country: "United States",
    status: "Inactive",
  },
  {
    id: "15c",
    customerName: "Oleg Povh",
    company: "Adobe",
    phoneNumber: "(056)645-787-79",
    email: "oleh@abobe.com",
    country: "Ukraine",
    status: "Active",
  },
  {
    id: "16c",
    customerName: "Anton Junk",
    company: "Facebook",
    phoneNumber: "(099)227-91-26",
    email: "ant@facebook.com",
    country: "United States",
    status: "Inactive",
  },
  {
    id: "17c",
    customerName: "Alisa Rebant",
    company: "Facebook",
    phoneNumber: "(097)277-091-16",
    email: "al@facebook.com",
    country: "United States",
    status: "Inactive",
  },
];
